### ISSUE TITLE
请教下RabbitMQ的高并发场景下，如何使用和配置

### ISSUE THREAD

**Issue by weiraneve** [fiuty/exercisegroup#1]
您好，我在网上看过您关于RabbitMQ的一些文章，结合上您开源的代码，我在自己设计项目里，想做个简单的秒杀系统设计。关于RabbitMQ的使用，若是使用单一消费者实例的配置没有问题，但我想用多个消费者实例的配置，则跑出来会有大量进入MQ的消息未被消费，思来想去，在此跟作者您请教下如何配置和书写。

**Comment by fiuty** [comment]
您好，在springboot中可以通过简单的配置来配置多消费者进行消费。可以通过配置好容器工厂，设置并发消费者实例的初始数量concurrentConsumers， 设置并发消费者实例的最大数量maxConcurrentConsumers，配置好bean之后在队列那边监听的时候加上指定的监听容器containerFactory来监听。按道理应该会比单一消费者消费消息更快的才对，不过也不是配置越多越好。你那边配置多消费者比单一消费者消费速度还慢吗？

**Comment by fiuty** [comment]
一般如果等待时间长（I/O型）任务的话，可以多配置一些消费者。如果是计算时间长的任务可以少设置一点消费者，不过具体还是要压测才行，会有阈值。还可以通过打日志计算时间来看具体的瓶颈在哪块，然后试着优化那部分代码。

**Comment by weiraneve** [comment]
您好，我通过一些对于多实例容器的配置试图来加快消费消息的速度，但最后的结果都是，一旦用上多实例容器进行多消费者消息的运行，MQ一定会漏掉大量的消息，这里我感觉是积压后，未能消费或者其他原因。我配置多消费者后，速度肯定加快了，但有效命中率也就是在消费者那成功消费的信息大大减少了。我暂时不知道是我配置是不是并不对。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月5日(星期三) 上午9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fiuty/exercisegroup] 请教下RabbitMQ的高并发场景下，如何使用和配置 (Issue #1)





 
您好，在springboot中可以通过简单的配置来配置多消费者进行消费。可以通过配置好容器工厂，设置并发消费者实例的初始数量concurrentConsumers， 设置并发消费者实例的最大数量maxConcurrentConsumers，配置好bean之后在队列那边监听的时候加上指定的监听容器containerFactory来监听。按道理应该会比单一消费者消费消息更快的才对，不过也不是配置越多越好。你那边配置多消费者比单一消费者消费速度还慢吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fiuty** [comment]
是指有大量的消息没被消费，然后也丢失了对吧？先排查下是否发送消息成功（在配rabbitTemplate的时候可以输出日志），然后再排查下是否消费成功，消费失败消息是不是被丢弃了（消息确认模式）？消息确认消费模式建议用manual，然后可以在消费消息的时候加上日志输出，同时在rabbitmq管理界面查看消费情况。可以配几个消费者，然后在消费消息的时候故意停顿下如sleep一会，发送10条消息，试试排查下问题。

**Comment by fiuty** [comment]
有没有可能是因为异常然后被你try catch掉了，这样就不会当做异常消息处理了，被当做正常消息被消费了。

**Comment by weiraneve** [comment]
您好，我现在也在排查是哪里出现问题。现在发现的一个情况就是，使用多实例容器配置的MQ，大量消息无法被消费且如果重启秒杀模块的服务，会出现消费一定数量的消息，几乎每次重启都会有一些消息消费，然后从打印台打印出来。并且里面的消息似乎是不断地在重新消费，每次重启都会重新开始消费某一部分的信息。这一点暂时不知道啥情况。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fiuty/exercisegroup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fiuty/exercisegroup] 请教下RabbitMQ的高并发场景下，如何使用和配置 (Issue #1)





 
是指有大量的消息没被消费，然后也丢失了对吧？先排查下是否发送消息成功（在配rabbitTemplate的时候可以输出日志），然后再排查下是否消费成功，消费失败消息是不是被丢弃了（消息确认模式）？消息确认消费模式建议用manual，然后可以在消费消息的时候加上日志输出，同时在rabbitmq管理界面查看消费情况。可以配几个消费者，然后在消费消息的时候故意停顿下如sleep一会，发送10条消息，试试排查下问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiraneve** [comment]
我的RabbitMq页面，队列显示这画面，感觉是不是没有ack应答呢，😂我对于MQ的这些东西了解的太少了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fiuty/exercisegroup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fiuty/exercisegroup] 请教下RabbitMQ的高并发场景下，如何使用和配置 (Issue #1)





 
是指有大量的消息没被消费，然后也丢失了对吧？先排查下是否发送消息成功（在配rabbitTemplate的时候可以输出日志），然后再排查下是否消费成功，消费失败消息是不是被丢弃了（消息确认模式）？消息确认消费模式建议用manual，然后可以在消费消息的时候加上日志输出，同时在rabbitmq管理界面查看消费情况。可以配几个消费者，然后在消费消息的时候故意停顿下如sleep一会，发送10条消息，试试排查下问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fiuty** [comment]
你的消息确认消费模式是哪一种？听起来是auto自动响应模式，然后消息消费的时候出现异常消息了，所以这条异常消息没处理完的话后续的消息是不会再消费了（异常消息会重新归入队列进行消费）。当你重启的时候，部分消息会被消费（消息顺序打乱了），直到又遇到异常消息，消费的时候出现异常，然后又停止消费了。

**Comment by weiraneve** [comment]
我这里配置的是MANUAL手动确认模式。







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "fiuty/exercisegroup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fiuty/exercisegroup] 请教下RabbitMQ的高并发场景下，如何使用和配置 (Issue #1)





 
你的消息确认消费模式是哪一种？听起来是auto自动响应模式，然后消息消费的时候出现异常消息了，所以这条异常消息没处理完的话后续的消息是不会再消费了（异常消息会重新归入队列进行消费）。当你重启的时候，部分消息会被消费（消息顺序打乱了），直到又遇到异常消息，消费的时候出现异常，然后又停止消费了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fiuty** [comment]
听起来是有消息处理的时候发生异常的，然后消息没被消费成功。

**Comment by weiraneve** [comment]
是的，我感觉也是这样，因为我看控制台里面，发送消息的打印信息都是正常的，也没有抛出错误。估计就是消费信息的时候出现什么问题了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fiuty/exercisegroup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fiuty/exercisegroup] 请教下RabbitMQ的高并发场景下，如何使用和配置 (Issue #1)





 
听起来是有消息处理的时候发生异常的，然后消息没被消费成功。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fiuty** [comment]
你可以try catch捕获异常，如果出现异常再输出日志，或者debug，有可能是异常日志没输出，建议debug下。

**Comment by weiraneve** [comment]
我的消费者这里的代码是这样的，我这也有try catch捕捉异常，但打印台都没有什么异常抛出




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fiuty/exercisegroup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fiuty/exercisegroup] 请教下RabbitMQ的高并发场景下，如何使用和配置 (Issue #1)





 
你可以try catch捕获异常，如果出现异常再输出日志，或者debug，有可能是异常日志没输出，建议debug下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiraneve** [comment]
切换回单实例重启服务就直接把消息队列里的那些消息全消费完了，但一旦使用多实例容器配置，就出问题，1000个消息只能一时消费几十个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fiuty/exercisegroup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fiuty/exercisegroup] 请教下RabbitMQ的高并发场景下，如何使用和配置 (Issue #1)





 
你可以try catch捕获异常，如果出现异常再输出日志，或者debug，有可能是异常日志没输出，建议debug下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fiuty** [comment]
没有代码确实很难定位问题，方便看下代码吗？方便的话留个QQ，晚上有空我加你QQ，看看代码。

**Comment by weiraneve** [comment]
好的，谢谢您的关注了。我的QQ是907221539，晚上我也有空的。代码我放在附件了，请您过目斧正。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fiuty/exercisegroup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fiuty/exercisegroup] 请教下RabbitMQ的高并发场景下，如何使用和配置 (Issue #1)





 
没有代码确实很难定位问题，方便看下代码吗？方便的话留个QQ，晚上有空我加你QQ，看看代码。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiraneve** [comment]
多谢作者的指点，问题已经解决。
